---
# tasks file for desktop install
#
- name: install
  ansible.builtin.apt:
    cache_valid_time: 86400
    name: "{{ (desktop_packages |default([]))
              + (('mate' in desktop_types) |ternary(desktop_mate_packages,[]))
              + (desktop_rdp |ternary(desktop_rdp_packages,[])) }}"
    state: present
