---
# roles/desktop/tasks/main.yml
#
- name: gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: set host facts
  ansible.builtin.set_fact:
    dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

- name: install
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "install_{{ ansible_os_family }}.yml"
    - "install.yml"

- name: set default target
  ansible.builtin.file:
    src: "{{ systemd_lib }}/system/{{ desktop_target_default }}"
    dest: /etc/systemd/system/default.target
    state: link
  notify:
    - systemd reload
    - systemd isolate target

- name: XDG config.
  ansible.builtin.include_tasks: xdg/configure.yml

- name: gnome desktop config.
  ansible.builtin.include_tasks: gnome/configure.yml

- name: apptainer
  block:
    - name: apptainer install
      ansible.builtin.include_tasks: apptainer/install-{{ ansible_os_family }}.yml
    - name: apptainer configuration
      ansible.builtin.include_tasks: apptainer/configure.yml
  when: [desktop_apptainer_enabled]

- name: eclipse install
  ansible.builtin.include_tasks: eclipse/install.yml
  when:
    - desktop_eclipse_enabled

- name: owncloud client install
  ansible.builtin.include_tasks: owncloud/install-{{ ansible_os_family }}.yml
  when:
    - desktop_owncloud_client_enabled

- name: conky installation
  block:
    - name: conky install
      ansible.builtin.include_tasks: conky/install-{{ ansible_os_family }}.yml
    - name: conky config.
      ansible.builtin.include_tasks: conky/configure.yml
  when:
    - desktop_conky_enabled

#- name: turbovnc install
#  when:
#    - desktop_turbovnc_enabled
