---
# tasks file for desktop
#
- name: gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  ignore_errors: true
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"

- name: install
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "install_{{ ansible_os_family }}.yml"
    - "install.yml"
